version: '3.8'

services:
  db:
    image: postgres:13
    network_mode: host
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: qwality
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    depends_on:
      - db

volumes:
  pgdata: