"""Add password reset fields to user

Revision ID: 248135475b53
Revises: 7bf4726c77d4
Create Date: 2025-04-26 23:00:45.535959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '248135475b53'
down_revision: Union[str, None] = '7bf4726c77d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('reset_token', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('reset_token_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'reset_token_expiry')
    op.drop_column('user', 'reset_token')
    # ### end Alembic commands ###
