"""delete reset token from user

Revision ID: 2a7f6df8f6a6
Revises: 58d28cd22f6b
Create Date: 2025-05-06 00:59:24.438630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a7f6df8f6a6'
down_revision: Union[str, None] = '58d28cd22f6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'reset_token')
    op.drop_column('user', 'reset_token_expiry')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('reset_token_expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('reset_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
