"""change camera preview_url to camera_url

Revision ID: 58d28cd22f6b
Revises: a3853d987036
Create Date: 2025-05-04 16:29:18.008059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58d28cd22f6b'
down_revision: Union[str, None] = 'a3853d987036'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camera', sa.Column('camera_url', sa.String(length=255), nullable=True))
    op.drop_column('camera', 'preview_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camera', sa.Column('preview_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('camera', 'camera_url')
    # ### end Alembic commands ###
