"""add deleted_at into camera model

Revision ID: 66a40cfdefc8
Revises: d2cea87b90d3
Create Date: 2025-05-15 20:30:54.831591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66a40cfdefc8'
down_revision: Union[str, None] = 'd2cea87b90d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camera', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('camera', 'deleted_at')
    # ### end Alembic commands ###
