"""change payment for freekassa

Revision ID: a395b66cebf0
Revises: cf84385630f2
Create Date: 2025-05-23 16:26:10.128554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a395b66cebf0'
down_revision: Union[str, None] = 'cf84385630f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('freekassa_id', sa.String(length=255), nullable=True))
    op.add_column('payment', sa.Column('currency', sa.String(length=10), nullable=False))
    op.add_column('payment', sa.Column('payment_method', sa.String(length=50), nullable=True))
    op.add_column('payment', sa.Column('payment_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'payment_metadata')
    op.drop_column('payment', 'payment_method')
    op.drop_column('payment', 'currency')
    op.drop_column('payment', 'freekassa_id')
    # ### end Alembic commands ###
