"""Add conf_threshold to client

Revision ID: b46aaeaca79c
Revises: bed5ae82c9d4
Create Date: 2025-04-30 01:27:16.888416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b46aaeaca79c'
down_revision: Union[str, None] = 'bed5ae82c9d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('conf_threshold', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'conf_threshold')
    # ### end Alembic commands ###
