"""add font_size and color_theme into user

Revision ID: cf84385630f2
Revises: 5dcba9830aa6
Create Date: 2025-05-16 21:00:45.926927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf84385630f2'
down_revision: Union[str, None] = '5dcba9830aa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('inspection_client_id_fkey', 'inspection', type_='foreignkey')
    op.create_foreign_key(None, 'inspection', 'client', ['client_id'], ['id'])
    op.add_column('user', sa.Column('color_theme', sa.String(length=20), nullable=False))
    op.add_column('user', sa.Column('font_size', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'font_size')
    op.drop_column('user', 'color_theme')
    op.drop_constraint(None, 'inspection', type_='foreignkey')
    op.create_foreign_key('inspection_client_id_fkey', 'inspection', 'user', ['client_id'], ['id'])
    # ### end Alembic commands ###
