"""change Inpsection user_id to client_id

Revision ID: d2cea87b90d3
Revises: 2a7f6df8f6a6
Create Date: 2025-05-15 15:06:14.636287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2cea87b90d3'
down_revision: Union[str, None] = '2a7f6df8f6a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspection', sa.Column('client_id', sa.Integer(), nullable=False))
    op.drop_constraint('inspection_user_id_fkey', 'inspection', type_='foreignkey')
    op.create_foreign_key(None, 'inspection', 'user', ['client_id'], ['id'])
    op.drop_column('inspection', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspection', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'inspection', type_='foreignkey')
    op.create_foreign_key('inspection_user_id_fkey', 'inspection', 'user', ['user_id'], ['id'])
    op.drop_column('inspection', 'client_id')
    # ### end Alembic commands ###
